### ISSUE TITLE
Poloniex disabled almost 3 weeks now.

### ISSUE THREAD

**Issue by gettingmad** [gridcoin/Gridcoin-Research#938] opened 2018-02-15 00:24 UTC
I attempted to send 2300 GRC from my QT Wallet to Poloniex over 2 weeks ago. I sent this GRC "2 days BEFORE" Poloniex decided to disable GRC due to the ridiculous forking issue. The GRC I sent has been in limbo and I have not had access to it since I sent it. I think I have been more than patient in opening this issue. I do not like opening issues for coins I support. If Poloniex is not re-enabled within 7 more days I will be uninstalling BOINC, leaving GRCPool and I will no longer support Gridcoin, ever again. Im done asking.

https://i.imgur.com/fbM4taM.png

**Comment by grctest** [comment] 2018-02-15 08:59
Ultimatums don't accelerate development.

**Comment by gettingmad** [comment] 2018-02-15 21:52
-1

**Comment by gettingmad** [comment] 2018-02-15 21:52
Tell you what, just take your time.

**Comment by Foggyx420** [comment] 2018-02-16 09:18
Could be constructive rather then attacking gridcoin.

You mention sending the coins two days before forking issues. 999 confirms is far less then 2 days. (~960 blocks a day). if your coins did reach 999 they would be still tradable as only deposits and withdrawals are disabled.

You mention the forking that we have been dealing with? Yes unfortunate and it has been a very challenging task at hand. 

You seem like you expect the exchanges to risk losses due to network instabilities to satisfy your choice of timing.

Have you verified that the coins were sent on the main chain and not possibly a fork?

Have you checked how many confirmations your wallet says it has regarding that transaction?

Have you synced up your wallet and ran `checkwallet` rpc command to see if your coins were actually sent on a fork instead of the main chain?

How about tell us the transaction ID or grc address so we can check to see if it was sent on the main chain or not.

I honestly have no clue why someone would send coins to an exchange during a mandatory trigger time or network instability times and expect to have no risk of delays.

If you feel the need to leave gridcoin that is your choice. 

We're a warm welcoming community and have many people helping during this time testing fixes.

If you for some reason (I'm clueless to this) uninstall boinc and punish scientific projects because your just in it for the coins that is your choice also.

Everyone is frustrated and on edge and working through this. Empty meaningless threats don't form solutions nor help the situation in any way.

While you make threats and post in the way you have; others have stepped up to help aid in solutions and move forward to get past this trying time. That is the gridcoin community I know.

Whether you leave or not your coins are either on the exchange for when things finally get completely sorted and it's confirmed or they still technically in your wallet if sent on a forked chain. Your coins may be in limbo but they are not lost. 

Have a wonderful day

**Comment by xaminmo** [comment] 2018-02-16 17:58
@gettingmad, the way to encourage people to work harder is to make them want to.  The devs get paid about  $30USD per hour in GRC, which seems pretty modest considering how much they don't bill.

If you want to help them out, and endear them to your frustrations, then send them some coins.  All of their addresses are in the cryptotalk forum for gridcoin developer compensation.

Rest asssured though, they have a vested interest in GRC being stable, and growing.  This is a serious issue for them.

**Comment by Foggyx420** [comment] 2018-02-16 18:36
Oddly enough despite your thought process on it they will be getting sum
coins for the testnet testing during this trying time. Feel free to join
testnet

**Comment by Pythonix** [comment] 2018-02-19 21:14
I think @denravonska should close this :)

**Closed** 2018-02-21 14:04 UTC
